In [4]:
import numpy as np

ADDITION

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

sum = a + b
sum


array([ 7,  9, 11, 13, 15])

SUBTRACTION

In [6]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

sum = a - b
sum

array([-5, -5, -5, -5, -5])

MULTIPLICATION

In [7]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

sum = a * b
sum

array([ 6, 14, 24, 36, 50])