In [23]:
import numpy as np

INSERTION OF DATA IN TO ARRAY IN 1D

In [24]:
a = np.array([1,2,3,4,5,6])
np.insert(a,[1,2,3],510)

array([  1, 510,   2, 510,   3, 510,   4,   5,   6])

INSERTION OF DATA INTO 2D ARRAY

In [28]:
b = np.array([[1,2,3],[4,5,6]])
# np.insert(b,2,[500,501,502], axis= 0)
c = np.append(b,[[7,8,9]], axis= 0)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

DELETION OF THE DATA FROM THE ARRAY

In [31]:
a = np.array([1,2,3,4,5,6])
print(len(a))
np.delete(a,5)

6


array([1, 2, 3, 4, 5])