In [28]:
import numpy as np

CREATING MATRIX 

In [29]:
a = np.matrix([[1,2,3],[4,5,6]])
b = np.matrix([[1,2,3],[4,5,6]])

print(type(a))

<class 'numpy.matrix'>


ARITHMETIC OPERATIONS WITH MATRIX

In [30]:
x = np.matrix([[1,2],[3,4]])
y = np.matrix([[1,2],[3,4]])
print(x.dot(y))

[[ 7 10]
 [15 22]]


FUNCTIONS OF MATRIX

In [36]:
print(np.transpose(a))
print()
print(np.swapaxes(a,0,1))
print()
print(np.linalg.inv(x))
print()
print(np.linalg.matrix_power(x,2))
print()
print(np.linalg.det(x))



[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[-2.   1. ]
 [ 1.5 -0.5]]

[[ 7 10]
 [15 22]]

-2.0000000000000004
