In [1]:
import numpy as np


In [7]:

l = []
for i in range(5):
    a = input('Enter 5 Fruits name: ')
    l.append(a)
    

print(np.array(l))
print(type(np.array(l)))



['1' '2' '3' '45' '5']
<class 'numpy.ndarray'>


THIS IS THE ONE DIMENSIONAL ARRAY

In [11]:
x = np.array([1,2,3,4])
print(x)
x.ndim

[1 2 3 4]


1

THIS IS THE TWO DIMENSIONAL ARRAY

In [12]:
y = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(y)
y.ndim

[[1 2 3 4 5]
 [1 2 3 4 5]]


2

THIS IS THE THREE DIMENSIONAL ARRARY


In [13]:
z = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])
print(z)
z.ndim

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


3

THIS SHOWS MULTI-DIMENSIONAL ARRAY

In [16]:
py = np.array([1,2,3,4,5,6,7,8,9], ndmin= 10)
print(py)
py.ndim

[[[[[[[[[[1 2 3 4 5 6 7 8 9]]]]]]]]]]


10