In [1]:
import numpy as np

SHUFFLE FUNCTION

In [3]:
a = np.array([1,2,3,4,5,6])
np.random.shuffle(a)
a

array([1, 5, 3, 6, 4, 2])

UNIQUE FUNCTION

In [4]:
b = np.array([1,2,3,6,2,1,4,53,6,5,1,1,2,2,2,3,4,5,4])
np.unique(b)

array([ 1,  2,  3,  4,  5,  6, 53])

RESIZE FUNCTION

In [9]:
b = np.array([1,2,3,4,5,6])
c = np.resize(b,(3,2))
c.flatten()

array([1, 2, 3, 4, 5, 6])