In [2]:
import numpy as np

CREATING AN ARRAY WITH RANDOM FUNCTION

RAND()


In [3]:
a = np.random.rand(5)
a

array([0.31017971, 0.30183313, 0.52169328, 0.58880272, 0.54777816])

RANDN()

In [4]:
b = np.random.randn(5)
b

array([-1.05619129, -0.1089534 , -1.93346424, -0.11125197,  0.4897527 ])

RANF()

In [6]:
c = np.random.ranf(5)
c

array([0.99855648, 0.60641671, 0.81435769, 0.19860498, 0.44141529])

RANDINT()

In [8]:
z = np.random.randint(0,20, size= 5)
z

array([ 6,  4,  3, 14,  9])